
name: Test os226

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        test:
          - batch
          - pool
          - syscall

    steps:
    - uses: actions/checkout@v2
    - run: cargo build
    - run: ./test/run.sh ${{matrix.test}}
